Upgraded to React Router V6
Heptagram-Bot-Project/website pull request #136
Opened 2022-05-05 17:43 UTC by Sam-Radnus

# Pull Request

## Description

Upgraded to React Router V6
## Related Issue

Closes #104 

## Version
Did you remember to update the version number in the package.json file?

- [ ] For a nmajor restructuring, or large changes please bump the the major version number. (ex: 1.x.x)
- [x] For a minor change, bump the minor version number. (ex: x.1.x)
- [ ] For a bug fix, bump the patch version number. (ex: x.x.1)

## Documentation

For _any_ version updates, please verify if the [documentation page](https://docs.beccalyria.com?utm_source=github&utm_medium=pr-template) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [x] My contribution does NOT require a documentation update.
- [x] My contribution DOES require a documentation update.

2022-05-05 21:37 UTC, MidouWebDev reviewed
Thanks a lot @Sam-Radnus for this PR, we really appreciate your contribution !
For the health page i guess, we do have a special url for it.
I guess it is : https://status.heptagrambotproject.com/
Can you confirm ? @j-dogcoder

2022-05-05 23:09 UTC, j-dogcoder commented
> Thanks a lot @Sam-Radnus for this PR, we really appreciate your contribution !
> For the health page i guess, we do have a special url for it.
> I guess it is : https://status.heptagrambotproject.com/
> Can you confirm ? @j-dogcoder

That is correct @MidouWebDev. I will take a look at this shortly.

2022-05-05 23:11 UTC, j-dogcoder approved these changes
LGTM!

2022-05-05 23:18 UTC, j-dogcoder requested changes
Actually, have some small issues that need to be fixed.

2022-05-05 23:18 UTC, j-dogcoder commented on src/Components/Footer.js
> +import {Link ,Navigate,useNavigate} from 'react-router-dom';
Hey, please remove `Navigate & useNavigate` here, as they are unused variables.
```suggestion
import {Link} from 'react-router-dom';
```

2022-05-05 23:18 UTC, j-dogcoder commented on src/Components/Header-Cmd.js
> +import {Link ,Navigate,useNavigate} from 'react-router-dom';
Hey, please remove Navigate & useNavigate here, as they are unused variables.

```suggestion
import {Link} from 'react-router-dom';
```

2022-05-05 23:18 UTC, j-dogcoder commented on src/Components/Header.js
> +import {Link ,Navigate,useNavigate} from 'react-router-dom';
Hey, please remove Navigate & useNavigate here, as they are unused variables.

```suggestion
import {Link} from 'react-router-dom';
```

2022-05-06 01:29 UTC, Sam-Radnus commented on src/Components/Header.js
> +import {Link ,Navigate,useNavigate} from 'react-router-dom';
Ok , @j-dogcoder

2022-05-06 02:00 UTC, j-dogcoder approved these changes

2022-05-06 02:01 UTC, merged

2022-05-06 02:01 UTC, j-dogcoder commented
### 🎉 Congratulations @Sam-Radnus! 🎉 

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labeled `help wanted` for additional opportunities to contribute.

**Discord Server:**
_We would love it if you joined our community discord server! Your contribution to the project make you eligible for special roles & perks._

2022-05-06 02:05 UTC, Sam-Radnus commented
Ok , @j-dogcoder ,I Loved working on the Website and I will make sure to join your discord server

2022-05-06 02:56 UTC, Sam-Radnus commented
Thank You Very Much

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Fri, 6 May 2022 at 07:32, Jasper Mayone ***@***.***> wrote:

> 🎉 Congratulations @Sam-Radnus <https://github.com/Sam-Radnus>! 🎉
>
> Congratulations on making your first pull request to our project. We have
> reviewed your contributions and are happy to accept them.
>
> We hope you enjoyed the contribution process, and encourage you to watch
> for issues labeled help wanted for additional opportunities to contribute.
>
> *Discord Server:*
> *We would love it if you joined our community discord server! Your
> contribution to the project make you eligible for special roles & perks.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Heptagram-Bot-Project/website/pull/136#issuecomment-1119195150>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQLYQFGMSGFHHSYNBPAIOJ3VIR4R5ANCNFSM5VFZEWWQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>